import config from '../../config.cjs';
const API_KEY = '33241c3a8402295fdc';
const BOT_THUMBNAIL = 'https://raw.githubusercontent.com/joeljamestech2/JOEL-XMD/refs/heads/main/mydata/media/joelXbot.jpg';

const gfxmaker = async (m, Matrix) => {
  const prefix = config.PREFIX;
  if (!m.body.startsWith(prefix)) return;

  const args = m.body.slice(prefix.length).trim().split(/\s+/);
  const cmd = args.shift().toLowerCase();
  const text = args.join(' ');
  const [text1, text2] = text.split('|').map(s => s?.trim());

  const soloTextCmds = {
    carbon: `https://api.nexoracle.com/image-creating/carbon-img?apikey=${API_KEY}&text=${encodeURIComponent(text)}`,
    gfx8: `https://api.nexoracle.com/image-creating/gfx9?apikey=${API_KEY}&text=${encodeURIComponent(text)}`,
    gfx9: `https://api.nexoracle.com/image-creating/gfx10?apikey=${API_KEY}&text=${encodeURIComponent(text)}`,
    gfx10: `https://api.nexoracle.com/image-creating/gfx12?apikey=${API_KEY}&text=${encodeURIComponent(text)}`,
    gfx11: `https://api.nexoracle.com/image-creating/gfx11?apikey=${API_KEY}&text=${encodeURIComponent(text)}`,
  };

  const dualTextCmds = {
    gfx: `https://api.nexoracle.com/image-creating/gfx?apikey=${API_KEY}&text1=${encodeURIComponent(text1)}&text2=${encodeURIComponent(text2)}`,
    gfx2: `https://api.nexoracle.com/image-creating/gfx2?apikey=${API_KEY}&text1=${encodeURIComponent(text1)}&text2=${encodeURIComponent(text2)}`,
    gfx3: `https://api.nexoracle.com/image-creating/gfx4?apikey=${API_KEY}&text1=${encodeURIComponent(text1)}&text2=${encodeURIComponent(text2)}`,
    gfx4: `https://api.nexoracle.com/image-creating/gfx5?apikey=${API_KEY}&text1=${encodeURIComponent(text1)}&text2=${encodeURIComponent(text2)}&text3=.`,
    gfx5: `https://api.nexoracle.com/image-creating/gfx6?apikey=${API_KEY}&text1=${encodeURIComponent(text1)}&text2=${encodeURIComponent(text2)}&text3=.`,
    gfx6: `https://api.nexoracle.com/image-creating/gfx7?apikey=${API_KEY}&text1=${encodeURIComponent(text1)}&text2=${encodeURIComponent(text2)}`,
    gfx7: `https://api.nexoracle.com/image-creating/gfx8?apikey=${API_KEY}&text1=${encodeURIComponent(text1)}&text2=${encodeURIComponent(text2)}`,
  };

  if (soloTextCmds[cmd]) {
    if (!text) {
      return Matrix.sendMessage(m.from, {
        text: '```Please provide text. Example:``` \n`' + prefix + cmd + ' Hello World`',
      }, { quoted: m });
    }

    return Matrix.sendMessage(m.from, {
      image: { url: soloTextCmds[cmd] },
      caption: '```Generated by JOEL XMD```',
      contextInfo: {
        isForwarded: true,
        forwardingScore: 999,
        externalAdReply: {
          title: 'ᴊᴏᴇʟ ʙᴏᴛ ɢғx',
          mediaType: 1,
          thumbnailUrl: BOT_THUMBNAIL,
          sourceUrl: 'https://whatsapp.com/channel/0029Vak2PevK0IBh2pKJPp2K'
        }
      }
    }, { quoted: m });
  }

  if (dualTextCmds[cmd]) {
    if (!text1 || !text2) {
      return Matrix.sendMessage(m.from, {
        text: '```Please provide text1 and text2 separated by |. Example:```\n`' + prefix + cmd + ' JOEL | XMD`',
      }, { quoted: m });
    }

    return Matrix.sendMessage(m.from, {
      image: { url: dualTextCmds[cmd] },
      caption: '```Generated by JOEL XMD```',
      contextInfo: {
        isForwarded: true,
        forwardingScore: 999,
        externalAdReply: {
          title: 'ᴊᴏᴇʟ ʙᴏᴛ ɢғx',
          mediaType: 1,
          thumbnailUrl: BOT_THUMBNAIL,
          sourceUrl: 'https://whatsapp.com/channel/0029Vak2PevK0IBh2pKJPp2K'
        }
      }
    }, { quoted: m });
  }
};

export default gfxmaker;
